<a href="https://colab.research.google.com/github/BavyaSree-C/BavyaSree-C/blob/main/BCG_X_task_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'Company': ['Microsoft', 'Microsoft', 'Microsoft', 'Tesla', 'Tesla', 'Tesla', 'Apple', 'Apple', 'Apple'],
    'Total Revenue': [245122, 211915, 198270, 97690, 96773, 81462, 391035, 383285, 394328],
    'Net Income': [88136, 72361, 72738, 7153, 14974, 12587, 93736, 96995, 99803 ],
    'Total Assets': [512163, 411976, 364840, 122070, 106618, 82338, 364980, 352583, 352755 ],
    'Total Liabilities': [243686, 205753, 198298, 48390, 43009, 36440, 308030, 290437, 302083	],
    'Cash Flow': [118548, 87582, 89035, 14923, 13256, 14724, 30737, 24977, 35929],
    'Year': [2024, 2023, 2022, 2024, 2023, 2022, 2024, 2023, 2022]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

,Company,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow,Year
0,Microsoft,245122,88136,512163,243686,118548,2024
1,Microsoft,211915,72361,411976,205753,87582,2023
2,Microsoft,198270,72738,364840,198298,89035,2022
3,Tesla,97690,7153,122070,48390,14923,2024
4,Tesla,96773,14974,106618,43009,13256,2023
5,Tesla,81462,12587,82338,36440,14724,2022
6,Apple,391035,93736,364980,308030,30737,2024
7,Apple,383285,96995,352583,290437,24977,2023
8,Apple,394328,99803,352755,302083,35929,2022

In [5]:
df['Revenue Growth (%)'] = df.groupby(['Company'])['Total Revenue'].pct_change() * 100
df['Net Income Growth (%)'] = df.groupby(['Company'])['Net Income'].pct_change() * 100

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Company                9 non-null      object
 1   Total Revenue          9 non-null      int64
 2   Net Income             9 non-null      int64
 3   Total Assets           9 non-null      int64
 4   Total Liabilities      9 non-null      int64
 5   Cash Flow              9 non-null      int64
 6   Year                   9 non-null      int64
 7   Revenue Growth (%)     6 non-null      float64
 8   Net Income Growth (%)  6 non-null      float64
dtypes: float64(2), int64(6), object(1)
memory usage: 780.0+ bytes

In [7]:
df = df.sort_values(by=['Company', 'Year'])

In [8]:
df['Assets Growth (%)'] = df.groupby('Company')['Total Assets'].pct_change() * 100
df['Liabilities Growth (%)'] = df.groupby('Company')['Total Liabilities'].pct_change() * 100
df['Cash Flow Growth (%)'] = df.groupby('Company')['Cash Flow'].pct_change() * 100

In [9]:
df

,Company,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow,Year,Revenue Growth (%),Net Income Growth (%),Assets Growth (%),Liabilities Growth (%),Cash Flow Growth (%)
8,Apple,394328,99803,352755,302083,35929,2022,2.881146,2.894995,NaN,NaN,NaN
7,Apple,383285,96995,352583,290437,24977,2023,-1.981920,3.476786,-0.048759,-3.855232,-30.482340
6,Apple,391035,93736,364980,308030,30737,2024,NaN,NaN,3.516052,6.057424,23.061216
2,Microsoft,198270,72738,364840,198298,89035,2022,-6.438902,0.520999,NaN,NaN,NaN
1,Microsoft,211915,72361,411976,205753,87582,2023,-13.547132,-17.898475,12.919636,3.759493,-1.631942
0,Microsoft,245122,88136,512163,243686,118548,2024,NaN,NaN,24.318650,18.436183,35.356580
5,Tesla,81462,12587,82338,36440,14724,2022,-15.821562,-15.940964,NaN,NaN,NaN
4,Tesla,96773,14974,106618,43009,13256,2023,-0.938684,109.338739,29.488207,18.026894,-9.970117
3,Tesla,97690,7153,122070,48390,14923,2024,NaN,NaN,14.492862,12.511335,12.575438

In [10]:
df.fillna(0,inplace=True)

In [11]:
df.reset_index(drop=True, inplace=True)

In [12]:
df.to_csv('final_BCG_report.csv')

In [13]:
df

,Company,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow,Year,Revenue Growth (%),Net Income Growth (%),Assets Growth (%),Liabilities Growth (%),Cash Flow Growth (%)
0,Apple,394328,99803,352755,302083,35929,2022,2.881146,2.894995,0.000000,0.000000,0.000000
1,Apple,383285,96995,352583,290437,24977,2023,-1.981920,3.476786,-0.048759,-3.855232,-30.482340
2,Apple,391035,93736,364980,308030,30737,2024,0.000000,0.000000,3.516052,6.057424,23.061216
3,Microsoft,198270,72738,364840,198298,89035,2022,-6.438902,0.520999,0.000000,0.000000,0.000000
4,Microsoft,211915,72361,411976,205753,87582,2023,-13.547132,-17.898475,12.919636,3.759493,-1.631942
5,Microsoft,245122,88136,512163,243686,118548,2024,0.000000,0.000000,24.318650,18.436183,35.356580
6,Tesla,81462,12587,82338,36440,14724,2022,-15.821562,-15.940964,0.000000,0.000000,0.000000
7,Tesla,96773,14974,106618,43009,13256,2023,-0.938684,109.338739,29.488207,18.026894,-9.970117
8,Tesla,97690,7153,122070,48390,14923,2024,0.000000,0.000000,14.492862,12.511335,12.575438

In [14]:
# Aggregate statistics for each company
agg_df = df.groupby('Company').agg({
    'Total Revenue': ['mean', 'max', 'min'],
    'Net Income': ['mean', 'max', 'min'],
    'Revenue Growth (%)': ['mean'],
    'Net Income Growth (%)': ['mean'],
    'Assets Growth (%)' : ['mean'],
    'Liabilities Growth (%)' : ['mean'],
    'Cash Flow Growth (%)' :['mean']
}).reset_index()

print(agg_df)

     Company  Total Revenue                    Net Income                \
                       mean     max     min          mean    max    min
0      Apple  389549.333333  394328  383285  96844.666667  99803  93736
1  Microsoft  218435.666667  245122  198270  77745.000000  88136  72361
2      Tesla   91975.000000   97690   81462  11571.333333  14974   7153

  Revenue Growth (%) Net Income Growth (%) Assets Growth (%)  \
                mean                  mean              mean
0           0.299742              2.123927          1.155764
1          -6.662011             -5.792492         12.412762
2          -5.586748             31.132592         14.660357

  Liabilities Growth (%) Cash Flow Growth (%)
                    mean                 mean
0               0.734064            -2.473708
1               7.398559            11.241546
2              10.179409             0.868440

In [15]:
agg_df

     Company  Total Revenue                    Net Income                \
                       mean     max     min          mean    max    min
0      Apple  389549.333333  394328  383285  96844.666667  99803  93736
1  Microsoft  218435.666667  245122  198270  77745.000000  88136  72361
2      Tesla   91975.000000   97690   81462  11571.333333  14974   7153

  Revenue Growth (%) Net Income Growth (%) Assets Growth (%)  \
                mean                  mean              mean
0           0.299742              2.123927          1.155764
1          -6.662011             -5.792492         12.412762
2          -5.586748             31.132592         14.660357

  Liabilities Growth (%) Cash Flow Growth (%)
                    mean                 mean
0               0.734064            -2.473708
1               7.398559            11.241546
2              10.179409             0.868440

In [16]:
agg_df.to_csv('Summary_final_report.csv')

🍏 Apple
✅ Highest revenue and strong asset base.

📈 Positive net income growth indicates improving profitability.

💸 Stable and healthy cash flow supports long-term sustainability.

⚖️ Good balance between assets and liabilities.

Inference: Apple is a mature and stable tech giant with consistent performance and strong financial health.

💻 Microsoft
📉 Both revenue and net income are declining, possibly due to temporary setbacks.

🧾 However, it maintains very high cash flow, suggesting operational excellence.

🛡️ Strong asset base and low debt risk.

Inference: Microsoft remains financially solid but may need to reignite growth strategies to reverse recent downward trends.

🚗 Tesla
🚀 Despite a drop in revenue, it shows a massive jump in net income – sign of improved efficiency.

📊 Operating cash flow is decent, supporting continued innovation.

🧮 Asset-to-liability ratio is healthy.

Inference: Tesla is maturing financially, shifting focus from rapid expansion to profit optimization.

# **FINANCIAL CHATBOT**

In [41]:
import CHATBOTT

In [42]:
CHATBOTT.run_chatbot()

Welcome to the AI Financial Chatbot!
I can answer your financial queries related to Apple, Tesla, or Microsoft (2022-2024).
------------------------------------------------------------------

Type 'hi' to start or 'exit' to quit: hi
Enter Company Name (Apple, Tesla, Microsoft): microsoft
Enter Fiscal Year (2022, 2023, or 2024): 2023

Ask your financial question (or type 'back' to change company/year): totalt revenue
The Total Revenue for Microsoft in 2023 is $ 211915

Ask your financial question (or type 'back' to change company/year): What is the Net Income?
The Net Income for Microsoft in 2023 is $ 72361

Ask your financial question (or type 'back' to change company/year): What is cash flow from operating activities?
Data not available or invalid input. Please check the company name, year, or try another query.

Ask your financial question (or type 'back' to change company/year): What is the revenue growth(%) ?
The Revenue Growth (%) for Microsoft in 2023 is -13.55%

Ask your financial question (or type 'back' to change company/year): What is the assets growth(%) ?
The Assets Growth (%) for Microsoft in 2023 is 12.92%

Ask your financial question (or type 'back' to change company/year): What is the year by year average revenue growth rate(%)?
The Revenue Growth (%) for Microsoft in 2023 is -13.55%

Ask your financial question (or type 'back' to change company/year): What is the year by year average liabilities growth rate(%)?
The Liabilities Growth (%) for Microsoft in 2023 is 3.76%

Ask your financial question (or type 'back' to change company/year): What is the year by year average cash flow from operations growth rate(%)?
Data not available or invalid input. Please check the company name, year, or try another query.

Ask your financial question (or type 'back' to change company/year): What is the year by year average liabilities growth rate(%)?
The Liabilities Growth (%) for Microsoft in 2023 is 3.76%

Ask your financial question (or type 'back' to change company/year): revenue
The Total Revenue for Microsoft in 2023 is $ 211915

Ask your financial question (or type 'back' to change company/year): net incomee
The Net Income for Microsoft in 2023 is $ 72361

Ask your financial question (or type 'back' to change company/year): back
------------------------------------------------------------------

Type 'hi' to start or 'exit' to quit: exit
Thank you for using the chatbot. Goodbye!

In [ ]:
from google.colab import files
uploaded=files.uploaded